### ISSUE TITLE
What is the point of this gem?

### ISSUE THREAD

**Issue by rafaelfranca** [rpanachi/core_ext#3]
I'm having a really hard time to understand why someone would need to fork active support to just copy the core extension code since you can already use active support and cherry pick only the extension you want. There is any reason besides that?

**Comment by rpanachi** [comment]
The motivation of this [wip] project is to ship a gem with some useful extensions to Ruby core. This was made initially from scratch, but I received a suggestion to fork the ActiveSupport and remove the parts that I don't want to be shipped. So I did it.

This gem is still in development. All references, credits, copyright and authorship was maintained. The efforts was to move all the classes under the `CoreExt` namespace and remove a lot of AS classes and code to make this gem more focused only on "core" part.

The objective is to be an option, not a replacement.
